[codestyle]
requirements = [ "latest python", "strict types", "use types hints like in statically typed", "solid", "dont use any comments or docstrings in code", "output only code block, no other text", "in arcade, dont use start_render() in on_draw, use clear"]
