[[feature]]
name = "window"
requirements = [ "prototype window for game",]

[[feature]]
name = "settings"
requirements = [ "data model, crud for settings",]

[[feature]]
name = "main_menu"
requirements = [ "game main menu",]

[[feature]]
name = "event_bus"
requirements = [ "decoupled events system",]