[[file]]
id = 5
feature = "window"
task = "game_window"
file_name = "game_window.py"
class_name = "GameWindow"
path = "src/game_window"

[[file]]
id = 10
feature = "window"
task = "game_view"
file_name = "game_view.py"
class_name = "GameView"
path = "src/game_window"

[[file]]
id = 4
feature = "main_menu"
task = "main_menu_view"
file_name = "main_menu_view.py"
class_name = "MainMenu"
path = "src/main_menu"

[[file]]
id = 6
feature = "main_menu"
task = "settings_menu_view"
file_name = "settings_menu_view.py"
class_name = "SettingsMenu"
path = "src/main_menu"

[[file]]
id = 8
feature = "main_menu"
task = "navigation_controller"
file_name = "menu_navigation.py"
class_name = "MenuNavigation"
path = "src/main_menu"

[[file]]
id = 9
feature = "main_menu"
task = "smoke_menu_navigation"
file_name = "smoke_menu_navigation.py"
path = "src/main_menu"

[[file]]
id = 11
feature = "car"
task = "simple_car_object"
file_name = "car.py"
path = "src/car"

[[file]]
id = 13
feature = "car"
task = "refactor_car"
file_name = "car_specs.py"
class_name = "CarSpecs"
path = "src/car"

[[file]]
id = 14
feature = "car"
task = "refactor_car"
file_name = "car_state.py"
class_name = "CarState"
path = "src/car"

[[file]]
id = 15
feature = "car"
task = "refactor_car"
file_name = "car_physics.py"
class_name = "CarPhysics"
path = "src/car"

[[file]]
id = 16
feature = "car"
task = "refactor_car"
file_name = "car_renderer.py"
class_name = "CarRenderer"
path = "src/car"

[[file]]
id = 17
feature = "car"
task = "refactor_car"
file_name = "car_input.py"
class_name = "CarInput"
path = "src/car"

[[file]]
id = 12
feature = "track"
task = "track_object"
file_name = "track.py"
path = "src/track"

[[file]]
id = 2
feature = "settings"
task = "data_model"
file_name = "settings.py"
class_name = "Settings"
path = "src/settings"

[[file]]
id = 3
feature = "settings"
task = "settings_crud"
file_name = "settings_crud.py"
class_name = "SettingsCRUD"
path = "src/settings"

[[file]]
id = 1
feature = "window"
task = "simple_example"
file_name = "simple_example.py"
class_name = "GameWindow"
path = "src/game_window"

[[file]]
id = 7
feature = "event_bus"
task = "event_bus_for_menu"
file_name = "event_bus.py"
class_name = "EventBus"
path = "src/event_bus"

