[[task]]
feature = "window"
name = "simple_example"
requirements = [ "game window", "1024x768", "ability to resize", "ability to maximalize", "ability of fullscreen", "title: Racing Track", "black background", "write white text in center: test",]
assigned_to = "implementer"
status = "tested"

[[task]]
feature = "settings"
name = "data_model"
requirements = [ "data_class", "fullscreen bool setting",]
assigned_to = "implementer"
status = "tested"

[[task]]
feature = "settings"
name = "settings_crud"
requirements = [ "class with crud for toml settings", "if file not exists, create", "fullscreen bool setting", "use data model", "load, save methods", "smoke test in script"]
assigned_to = "implementer"
status = "tested"

